server:
  port: 8080
  forward-headers-strategy: native

spring:

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  datasource:
    url: ${secrets.DB_URL}
    username: ${secrets.DB_USERNAME}
    password: ${secrets.DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${secrets.REDIS_HOST}
      port: ${secrets.REDIS_PORT}
      password: ${secrets.REDIS_PASSWORD}

  jpa:
    database: mysql
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
    show-sql: false

  cloud:
    gcp:
      project-id: bigtablet-homepage
      credentials:
        location: classpath:bigtablet-homepage-ffe77aff799f.json
      storage:
        bucket: bigtablet-homepage

  mail:
    host: smtp.gmail.com
    port: ${secrets.SMTP_PORT}
    email_noreply: ${secrets.SMTP_EMAIL_NOREPLY}
    password_noreply: ${secrets.SMTP_PASSWORD_NOREPLY}
    email_recruit: ${secrets.SMTP_EMAIL_RECRUIT}
    password_recruit: ${secrets.SMTP_PASSWORD_RECRUIT}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.connectiontimeout: 10000
      mail.smtp.timeout: 10000
      mail.smtp.writetimeout: 10000

application:
  jwt:
    secretKey: ${secrets.JWT_SECRET_KEY}
    expiration: 86400000
    refreshExpiration: 604800000